name: Pipeline CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Nextflow
      run: |
        curl -fsSL get.nextflow.io | bash -e
    - name: Run pipeline
      run: |
        .github/workflows/ci.sh run -with-docker
    - name: Validate pipeline results
      run: |
        .github/workflows/ci.sh validate
